// projects/taskflow-angular/src/frontend/src/app/components/create-project-modal/create-project-modal.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-create-project-modal',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './create-project-modal.component.html'
})
export class CreateProjectModalComponent implements OnChanges {
  @Input() visible = false;
  @Output() closed = new EventEmitter<void>();
  @Output() created = new EventEmitter<{ name: string; description?: string }>();

  private fb = inject(FormBuilder);

  form: FormGroup = this.fb.group({
    name: ['', [Validators.required, Validators.maxLength(200)]],
    description: ['']
  });

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['visible'] && changes['visible'].currentValue === true) {
      this.form.reset({ name: '', description: '' });
    }
  }

  submit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }
    const { name, description } = this.form.value;
    this.created.emit({ name: name.trim(), description: description?.trim() || undefined });
    this.form.reset({ name: '', description: '' });
  }

  get nameControl() {
    return this.form.get('name')!;
  }
}

@if (visible) {
  <div
    class="fixed inset-0 z-50 flex items-center justify-center p-4"
    (click)="closed.emit()"
    role="dialog"
    aria-modal="true"
  >
    <!-- Backdrop -->
    <div class="absolute inset-0 bg-black/40 backdrop-blur-sm"></div>

    <!-- Modal panel -->
    <div
      class="relative z-10 bg-white rounded-2xl shadow-xl w-full max-w-md p-6"
      (click)="$event.stopPropagation()"
    >
      <div class="flex items-center justify-between mb-5">
        <h2 class="font-display font-semibold text-lg text-slate-800">New Project</h2>
        <button
          type="button"
          (click)="closed.emit()"
          class="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
        >
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <form [formGroup]="form" (ngSubmit)="submit()" novalidate>
        <div class="flex flex-col gap-4">
          <!-- Name field -->
          <div>
            <label for="project-name" class="block text-sm font-medium text-slate-700 mb-1.5">
              Project Name <span class="text-danger">*</span>
            </label>
            <input
              id="project-name"
              type="text"
              formControlName="name"
              class="input"
              placeholder="Enter project name"
              autocomplete="off"
            />
            @if (nameControl.touched && nameControl.hasError('required')) {
              <p class="mt-1 text-xs text-danger">Project name is required.</p>
            }
            @if (nameControl.touched && nameControl.hasError('maxlength')) {
              <p class="mt-1 text-xs text-danger">Project name must be 200 characters or fewer.</p>
            }
          </div>

          <!-- Description field -->
          <div>
            <label for="project-description" class="block text-sm font-medium text-slate-700 mb-1.5">
              Description <span class="text-slate-400 font-normal">(optional)</span>
            </label>
            <textarea
              id="project-description"
              formControlName="description"
              class="input resize-none"
              rows="3"
              placeholder="Describe what this project is about"
            ></textarea>
          </div>
        </div>

        <div class="flex justify-end gap-3 mt-6">
          <button type="button" (click)="closed.emit()" class="btn-ghost">Cancel</button>
          <button type="submit" class="btn-primary" [disabled]="form.invalid">
            Create Project
          </button>
        </div>
      </form>
    </div>
  </div>
}

// projects/taskflow/src/frontend/src/components/CreateProjectModal.tsx
import { useState } from 'react'
import { X } from 'lucide-react'
import { useCreateProject } from '../hooks/useProjects'

interface CreateProjectModalProps {
  open: boolean
  onClose: () => void
}

export default function CreateProjectModal({ open, onClose }: CreateProjectModalProps) {
  const [name, setName] = useState('')
  const [description, setDescription] = useState('')
  const [error, setError] = useState<string | null>(null)
  const createProject = useCreateProject()

  if (!open) return null

  const handleSubmit = (e: { preventDefault: () => void }) => {
    e.preventDefault()
    if (!name.trim()) return
    setError(null)
    createProject.mutate(
      { name: name.trim(), description: description.trim() || undefined },
      {
        onSuccess: () => {
          setName('')
          setDescription('')
          setError(null)
          onClose()
        },
        onError: (err: Error) => {
          setError(err.message || 'Failed to create project. Please try again.')
        },
      },
    )
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/40 backdrop-blur-sm">
      <div className="card w-full max-w-md mx-4">
        <div className="flex items-center justify-between mb-5">
          <h2 className="font-display text-lg font-bold">New Project</h2>
          <button onClick={onClose} className="btn-ghost p-1.5 rounded-full">
            <X size={18} />
          </button>
        </div>

        <div className="flex flex-col gap-4">
          <div>
            <label className="block text-xs font-medium text-slate-500 mb-1.5">Project name</label>
            <input
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. Website Redesign"
              className="input"
              autoFocus
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-slate-500 mb-1.5">Description (optional)</label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="What's this project about?"
              className="input min-h-[80px] resize-none"
              rows={3}
            />
          </div>
          {error && (
            <p className="text-xs text-red-500">{error}</p>
          )}
          <div className="flex justify-end gap-2 pt-2">
            <button onClick={onClose} className="btn-ghost">Cancel</button>
            <button
              onClick={handleSubmit}
              disabled={!name.trim() || createProject.isPending}
              className="btn-primary disabled:opacity-50"
            >
              Create Project
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
