// projects/taskflow-angular/src/frontend/src/app/components/task-card/task-card.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Task, TaskStatus } from '../../models/types';
import { StatusBadgeComponent } from '../badges/status-badge.component';
import { PriorityBadgeComponent } from '../badges/priority-badge.component';

@Component({
  selector: 'app-task-card',
  standalone: true,
  imports: [CommonModule, StatusBadgeComponent, PriorityBadgeComponent],
  templateUrl: './task-card.component.html'
})
export class TaskCardComponent {
  @Input() task!: Task;
  @Output() statusChange = new EventEmitter<TaskStatus>();
  @Output() deleted = new EventEmitter<void>();

  cycleStatus(): void {
    const next: Record<TaskStatus, TaskStatus> = {
      TODO: 'IN_PROGRESS',
      IN_PROGRESS: 'DONE',
      DONE: 'TODO'
    };
    this.statusChange.emit(next[this.task.status]);
  }
}

<div class="bg-white rounded-lg border border-slate-200 p-4 flex flex-col gap-2 shadow-sm hover:shadow-md transition-shadow">
  <div class="flex items-start justify-between gap-2">
    <h4 class="text-sm font-medium text-slate-800 leading-snug flex-1">{{ task.title }}</h4>
    <button
      (click)="deleted.emit()"
      class="shrink-0 p-1 rounded text-slate-400 hover:text-danger hover:bg-red-50 transition-colors"
      title="Delete task"
      type="button"
    >
      <svg xmlns="http://www.w3.org/2000/svg" class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>
  </div>

  @if (task.description) {
    <p class="text-xs text-slate-500 line-clamp-2">{{ task.description }}</p>
  }

  <div class="flex items-center gap-2 flex-wrap mt-1">
    <button
      (click)="cycleStatus()"
      type="button"
      class="cursor-pointer transition-opacity hover:opacity-75"
      title="Click to advance status"
    >
      <app-status-badge [status]="task.status" />
    </button>
    <app-priority-badge [priority]="task.priority" />
  </div>
</div>

// projects/taskflow/src/frontend/src/components/TaskCard.tsx
import { Trash2, GripVertical } from 'lucide-react'
import { StatusBadge, PriorityBadge } from './Badges'
import type { Task, TaskStatus } from '../utils/types'
import { useUpdateTask, useDeleteTask } from '../hooks/useTasks'

interface TaskCardProps {
  task: Task
}

const nextStatus: Record<TaskStatus, TaskStatus> = {
  todo: 'in_progress',
  in_progress: 'done',
  done: 'todo',
}

export default function TaskCard({ task }: TaskCardProps) {
  const updateTask = useUpdateTask()
  const deleteTask = useDeleteTask()

  const cycleStatus = () => {
    updateTask.mutate({ id: task.id, status: nextStatus[task.status] } as never)
  }

  return (
    <div className="card group flex items-start gap-3 hover:shadow-md transition-shadow">
      <button className="mt-1 cursor-grab text-slate-300 opacity-0 group-hover:opacity-100 transition-opacity">
        <GripVertical size={16} />
      </button>

      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 mb-1">
          <h3 className="text-sm font-semibold truncate">{task.title}</h3>
        </div>

        {task.description && (
          <p className="text-xs text-slate-400 truncate mb-2">{task.description}</p>
        )}

        <div className="flex items-center gap-2">
          <button onClick={cycleStatus} title="Click to cycle status">
            <StatusBadge status={task.status} />
          </button>
          <PriorityBadge priority={task.priority} />
        </div>
      </div>

      <button
        onClick={() => deleteTask.mutate(task.id)}
        className="mt-1 text-slate-300 opacity-0 group-hover:opacity-100 hover:text-danger transition-all"
        title="Delete task"
      >
        <Trash2 size={15} />
      </button>
    </div>
  )
}
